-- =============================================================================
-- V001__create_spring_batch_schema.sql
-- =============================================================================
-- Flyway migration — Spring Batch 5.x job repository tables for Oracle.
--
-- Run as: CDP_LOADER (application user — NOT SYSDBA)
-- Connected to: FREEPDB1 via jdbc:oracle:thin:@//localhost:1521/FREEPDB1
--
-- Source: spring-batch-core-5.x  org/springframework/batch/core/schema-oracle10g.sql
-- Reproduced verbatim so Flyway manages lifecycle (spring.batch.jdbc.initialize-schema=never).
--
-- Prerequisite: infra/oracle/00-dba-bootstrap.sql must have been run as SYSDBA.
-- =============================================================================

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ  MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ            MAXVALUE 9223372036854775807 NOCYCLE;

CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION         NUMBER(19,0),
    JOB_NAME        VARCHAR2(100) NOT NULL,
    JOB_KEY         VARCHAR2(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID           NUMBER(19,0)   NOT NULL PRIMARY KEY,
    VERSION                    NUMBER(19,0),
    JOB_INSTANCE_ID            NUMBER(19,0)   NOT NULL,
    CREATE_TIME                TIMESTAMP      NOT NULL,
    START_TIME                 TIMESTAMP      DEFAULT NULL,
    END_TIME                   TIMESTAMP      DEFAULT NULL,
    STATUS                     VARCHAR2(10),
    EXIT_CODE                  VARCHAR2(2500),
    EXIT_MESSAGE               VARCHAR2(2500),
    LAST_UPDATED               TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL,
    PARAMETER_NAME   VARCHAR2(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR2(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR2(2500),
    IDENTIFYING      CHAR(1)       NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID          NUMBER(19,0)   NOT NULL PRIMARY KEY,
    VERSION                    NUMBER(19,0)   NOT NULL,
    STEP_NAME                  VARCHAR2(100)  NOT NULL,
    JOB_EXECUTION_ID           NUMBER(19,0)   NOT NULL,
    CREATE_TIME                TIMESTAMP      NOT NULL,
    START_TIME                 TIMESTAMP      DEFAULT NULL,
    END_TIME                   TIMESTAMP      DEFAULT NULL,
    STATUS                     VARCHAR2(10),
    COMMIT_COUNT               NUMBER(19,0),
    READ_COUNT                 NUMBER(19,0),
    FILTER_COUNT               NUMBER(19,0),
    WRITE_COUNT                NUMBER(19,0),
    READ_SKIP_COUNT            NUMBER(19,0),
    WRITE_SKIP_COUNT           NUMBER(19,0),
    PROCESS_SKIP_COUNT         NUMBER(19,0),
    ROLLBACK_COUNT             NUMBER(19,0),
    EXIT_CODE                  VARCHAR2(2500),
    EXIT_MESSAGE               VARCHAR2(2500),
    LAST_UPDATED               TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID   NUMBER(19,0)   NOT NULL PRIMARY KEY,
    SHORT_CONTEXT       VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT  CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID    NUMBER(19,0)   NOT NULL PRIMARY KEY,
    SHORT_CONTEXT       VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT  CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);
