-- =============================================================================
-- Daily Load Simulation — Round 19
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Reinstatement of suspended accounts + new residential wave
-- REJECTION REJ-D2: invalid email format (VR-CONT-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 18 (daily-round-18.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 19a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R19-001', 'Sabrina',  'Fontaine',   'ACTIVE', 'RESIDENTIAL', 'FR'),
    ('CUST-SIM-R19-002', 'Oluwaseun','Adebayo',    'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R19-003', 'Henrik',   'Magnusson',  'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R19-004', 'Zhen',     'Liu',         'ACTIVE', 'COMMERCIAL',  'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 19b. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R19-001E', 'CUST-SIM-R19-001', 'EMAIL', 'sabrina.fontaine@demo.com'),
    ('CC-SIM-R19-002E', 'CUST-SIM-R19-002', 'EMAIL', 'oluwaseun.adebayo@demo.com'),
    ('CC-SIM-R19-003E', 'CUST-SIM-R19-003', 'EMAIL', 'henrik.magnusson@demo.com'),
    ('CC-SIM-R19-004E', 'CUST-SIM-R19-004', 'EMAIL', 'zhen.liu@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 19c. Rejection: invalid email
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CC-SIM-R19-REJE', 'CUST-SIM-R19-001', 'EMAIL', 'sabrina.fontaine@@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = 'CC-SIM-R19-REJE');

-- 19d. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R19-001', 'CUST-SIM-R19-001', 'ACCT-SIM-R19-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R19-002', 'CUST-SIM-R19-002', 'ACCT-SIM-R19-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R19-003', 'CUST-SIM-R19-003', 'ACCT-SIM-R19-003', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R19-004', 'CUST-SIM-R19-004', 'ACCT-SIM-R19-004', 'ACTIVE', 'ELECTRIC', 'SMALL_COMMERCIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 19e. Reinstate suspended accounts from Round 18
UPDATE CUSTOMER.ENERGY_ACCOUNT
SET ACCOUNT_STATUS = 'ACTIVE', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE ENERGY_ACCOUNT_ID IN ('EA-SIM-R14-003', 'EA-SIM-R14-004');

-- 19f. Reactivate customer inactivated in Round 18
UPDATE CUSTOMER.CUSTOMER
SET ACCOUNT_STATUS = 'ACTIVE', STATUS_REASON = NULL,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CUSTOMER_ID = 'CUST-SIM-R13-004';

-- Verification
SELECT 'R19 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R19-%'
UNION ALL
SELECT 'R19 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R19-%';
