-- =============================================================================
-- Daily Load Simulation — Round 13
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Account closures + re-openings + new residential wave
-- REJECTION REJ-D2: invalid email format (VR-CONT-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 12 (daily-round-12.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 13a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R13-001', 'Elena',    'Popescu',    'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R13-002', 'Kwabena',  'Mensah',     'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R13-003', 'Rina',     'Hashimoto',  'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R13-004', 'Patrick',  'O''Sullivan','ACTIVE', 'COMMERCIAL',  'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 13b. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R13-001E', 'CUST-SIM-R13-001', 'EMAIL', 'elena.popescu@demo.com'),
    ('CC-SIM-R13-002E', 'CUST-SIM-R13-002', 'EMAIL', 'kwabena.mensah@demo.com'),
    ('CC-SIM-R13-003E', 'CUST-SIM-R13-003', 'EMAIL', 'rina.hashimoto@demo.com'),
    ('CC-SIM-R13-004E', 'CUST-SIM-R13-004', 'EMAIL', 'patrick.osullivan@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 13c. Rejection: invalid email — no domain suffix
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CC-SIM-R13-REJE', 'CUST-SIM-R13-001', 'EMAIL', 'elena@')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = 'CC-SIM-R13-REJE');

-- 13d. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R13-001', 'CUST-SIM-R13-001', 'ACCT-SIM-R13-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R13-002', 'CUST-SIM-R13-002', 'ACCT-SIM-R13-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R13-003', 'CUST-SIM-R13-003', 'ACCT-SIM-R13-003', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R13-004', 'CUST-SIM-R13-004', 'ACCT-SIM-R13-004', 'ACTIVE', 'ELECTRIC', 'SMALL_COMMERCIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 13e. Close accounts from Round 5 (customer moved away)
UPDATE CUSTOMER.ENERGY_ACCOUNT
SET ACCOUNT_STATUS = 'CLOSED', CLOSE_DATE = CURRENT_DATE(), UPDATED_AT = CURRENT_TIMESTAMP()
WHERE ENERGY_ACCOUNT_ID IN ('EA-SIM-R5-001', 'EA-SIM-R5-002');

-- 13f. Reactivate a previously suspended account from Round 9
UPDATE CUSTOMER.ENERGY_ACCOUNT
SET ACCOUNT_STATUS = 'ACTIVE', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE ENERGY_ACCOUNT_ID = 'EA-SIM-R9-003';

-- Verification
SELECT 'R13 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R13-%'
UNION ALL
SELECT 'R13 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R13-%';
