-- =============================================================================
-- Daily Load Simulation — Round 14
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Bulk language preference migration + new commercial wave
-- REJECTION REJ-D1: blank FIRST_NAME (VR-CUST-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 13 (daily-round-13.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 14a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R14-001', 'Nour',      'Khalil',     'ACTIVE', 'RESIDENTIAL', 'AR'),
    ('CUST-SIM-R14-002', 'Sebastien', 'Moreau',     'ACTIVE', 'RESIDENTIAL', 'FR'),
    ('CUST-SIM-R14-003', 'Adaeze',    'Eze',         'ACTIVE', 'COMMERCIAL',  'EN'),
    ('CUST-SIM-R14-004', 'Viktor',    'Hoffmann',   'ACTIVE', 'COMMERCIAL',  'DE')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 14b. Rejection: blank FIRST_NAME
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CUST-SIM-R14-REJ', '', 'BlankFirst', 'ACTIVE', 'COMMERCIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = 'CUST-SIM-R14-REJ');

-- 14c. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R14-001E', 'CUST-SIM-R14-001', 'EMAIL', 'nour.khalil@demo.com'),
    ('CC-SIM-R14-002E', 'CUST-SIM-R14-002', 'EMAIL', 'sebastien.moreau@demo.com'),
    ('CC-SIM-R14-003E', 'CUST-SIM-R14-003', 'EMAIL', 'adaeze.eze@demo.com'),
    ('CC-SIM-R14-004E', 'CUST-SIM-R14-004', 'EMAIL', 'viktor.hoffmann@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 14d. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R14-001', 'CUST-SIM-R14-001', 'ACCT-SIM-R14-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R14-002', 'CUST-SIM-R14-002', 'ACCT-SIM-R14-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R14-003', 'CUST-SIM-R14-003', 'ACCT-SIM-R14-003', 'ACTIVE', 'ELECTRIC', 'MEDIUM_COMMERCIAL'),
    ('EA-SIM-R14-004', 'CUST-SIM-R14-004', 'ACCT-SIM-R14-004', 'ACTIVE', 'ELECTRIC', 'MEDIUM_COMMERCIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 14e. Bulk language migration — all EN residents from Rounds 13 to FR
UPDATE CUSTOMER.CUSTOMER
SET PREFERRED_LANGUAGE = 'ES', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CUSTOMER_ID IN ('CUST-SIM-R13-001', 'CUST-SIM-R13-002', 'CUST-SIM-R13-003');

-- 14f. Update Round 12 solar customers — verify emails
UPDATE CUSTOMER.CUSTOMER_CONTACT
SET IS_VERIFIED = TRUE, UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CONTACT_ID IN ('CC-SIM-R12-001E', 'CC-SIM-R12-002E', 'CC-SIM-R12-003E');

-- Verification
SELECT 'R14 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R14-%'
UNION ALL
SELECT 'R14 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R14-%';
