-- =============================================================================
-- Daily Load Simulation — Round 11
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  New industrial customer batch — 4 customers, energy accounts, emails
-- REJECTION REJ-D1: blank FIRST_NAME (VR-CUST-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Rounds 1-10 (demo-daily-load-simulation.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 11a. New industrial customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R11-001', 'Tariq',    'Okafor',    'ACTIVE', 'INDUSTRIAL',  'EN'),
    ('CUST-SIM-R11-002', 'Svetlana', 'Volkov',    'ACTIVE', 'INDUSTRIAL',  'EN'),
    ('CUST-SIM-R11-003', 'Diego',    'Alvarado',  'ACTIVE', 'COMMERCIAL',  'EN'),
    ('CUST-SIM-R11-004', 'Fiona',    'Macgregor', 'ACTIVE', 'RESIDENTIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 11b. Rejection: blank FIRST_NAME
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CUST-SIM-R11-REJ', '', 'NoName', 'ACTIVE', 'RESIDENTIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = 'CUST-SIM-R11-REJ');

-- 11c. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R11-001E', 'CUST-SIM-R11-001', 'EMAIL', 'tariq.okafor@demo.com'),
    ('CC-SIM-R11-002E', 'CUST-SIM-R11-002', 'EMAIL', 'svetlana.volkov@demo.com'),
    ('CC-SIM-R11-003E', 'CUST-SIM-R11-003', 'EMAIL', 'diego.alvarado@demo.com'),
    ('CC-SIM-R11-004E', 'CUST-SIM-R11-004', 'EMAIL', 'fiona.macgregor@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 11d. Rejection: invalid email (no @)
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CC-SIM-R11-REJE', 'CUST-SIM-R11-001', 'EMAIL', 'not.valid.email')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = 'CC-SIM-R11-REJE');

-- 11e. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R11-001', 'CUST-SIM-R11-001', 'ACCT-SIM-R11-001', 'ACTIVE', 'ELECTRIC', 'LARGE_INDUSTRIAL'),
    ('EA-SIM-R11-002', 'CUST-SIM-R11-002', 'ACCT-SIM-R11-002', 'ACTIVE', 'ELECTRIC', 'LARGE_INDUSTRIAL'),
    ('EA-SIM-R11-003', 'CUST-SIM-R11-003', 'ACCT-SIM-R11-003', 'ACTIVE', 'ELECTRIC', 'SMALL_COMMERCIAL'),
    ('EA-SIM-R11-004', 'CUST-SIM-R11-004', 'ACCT-SIM-R11-004', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 11f. Update Round 10 customers — language preference change
UPDATE CUSTOMER.CUSTOMER
SET PREFERRED_LANGUAGE = 'DE', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CUSTOMER_ID IN ('CUST-SIM-R10-001', 'CUST-SIM-R10-002');

-- Verification
SELECT 'R11 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R11-%'
UNION ALL
SELECT 'R11 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R11-%';
