-- =============================================================================
-- Daily Load Simulation — Round 16
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Customer type changes (residential → commercial upgrade)
-- REJECTION REJ-D1: blank FIRST_NAME (VR-CUST-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 15 (daily-round-15.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 16a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R16-001', 'Ananya',   'Krishnaswamy', 'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R16-002', 'Brendan',  'Fitzpatrick',  'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R16-003', 'Layla',    'Nasser',       'ACTIVE', 'COMMERCIAL',  'EN'),
    ('CUST-SIM-R16-004', 'Mikael',   'Lindstrom',    'ACTIVE', 'RESIDENTIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 16b. Rejection: blank FIRST_NAME
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CUST-SIM-R16-REJ', '', 'Ghost', 'ACTIVE', 'RESIDENTIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = 'CUST-SIM-R16-REJ');

-- 16c. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R16-001E', 'CUST-SIM-R16-001', 'EMAIL', 'ananya.krishnaswamy@demo.com'),
    ('CC-SIM-R16-002E', 'CUST-SIM-R16-002', 'EMAIL', 'brendan.fitzpatrick@demo.com'),
    ('CC-SIM-R16-003E', 'CUST-SIM-R16-003', 'EMAIL', 'layla.nasser@demo.com'),
    ('CC-SIM-R16-004E', 'CUST-SIM-R16-004', 'EMAIL', 'mikael.lindstrom@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 16d. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R16-001', 'CUST-SIM-R16-001', 'ACCT-SIM-R16-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R16-002', 'CUST-SIM-R16-002', 'ACCT-SIM-R16-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R16-003', 'CUST-SIM-R16-003', 'ACCT-SIM-R16-003', 'ACTIVE', 'ELECTRIC', 'MEDIUM_COMMERCIAL'),
    ('EA-SIM-R16-004', 'CUST-SIM-R16-004', 'ACCT-SIM-R16-004', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 16e. Upgrade Round 15 residential customers to COMMERCIAL type (business registration)
UPDATE CUSTOMER.CUSTOMER
SET CUSTOMER_TYPE = 'COMMERCIAL', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CUSTOMER_ID IN ('CUST-SIM-R15-002', 'CUST-SIM-R15-004');

-- 16f. Update corresponding account rate class
UPDATE CUSTOMER.ENERGY_ACCOUNT
SET RATE_CLASS = 'SMALL_COMMERCIAL', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE ENERGY_ACCOUNT_ID IN ('EA-SIM-R15-002', 'EA-SIM-R15-004');

-- Verification
SELECT 'R16 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R16-%'
UNION ALL
SELECT 'R16 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R16-%';
