-- =============================================================================
-- Daily Load Simulation — Round 17
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Mass surname update (married names) + new residential cohort
-- REJECTION REJ-D2: invalid email format (VR-CONT-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 16 (daily-round-16.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 17a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R17-001', 'Priscilla', 'Nakamura',  'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R17-002', 'Emeka',     'Obi',        'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R17-003', 'Greta',     'Svensson',   'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R17-004', 'Rustam',    'Nazarov',    'ACTIVE', 'INDUSTRIAL',  'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 17b. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R17-001E', 'CUST-SIM-R17-001', 'EMAIL', 'priscilla.nakamura@demo.com'),
    ('CC-SIM-R17-002E', 'CUST-SIM-R17-002', 'EMAIL', 'emeka.obi@demo.com'),
    ('CC-SIM-R17-003E', 'CUST-SIM-R17-003', 'EMAIL', 'greta.svensson@demo.com'),
    ('CC-SIM-R17-004E', 'CUST-SIM-R17-004', 'EMAIL', 'rustam.nazarov@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 17c. Rejection: invalid email
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CC-SIM-R17-REJE', 'CUST-SIM-R17-001', 'EMAIL', 'priscilla_nakamura')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = 'CC-SIM-R17-REJE');

-- 17d. Energy accounts
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R17-001', 'CUST-SIM-R17-001', 'ACCT-SIM-R17-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R17-002', 'CUST-SIM-R17-002', 'ACCT-SIM-R17-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R17-003', 'CUST-SIM-R17-003', 'ACCT-SIM-R17-003', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R17-004', 'CUST-SIM-R17-004', 'ACCT-SIM-R17-004', 'ACTIVE', 'ELECTRIC', 'LARGE_INDUSTRIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 17e. Mass surname update — married name changes for Round 16 customers
UPDATE CUSTOMER.CUSTOMER SET LAST_NAME = 'Krishnaswamy-Rao',  UPDATED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = 'CUST-SIM-R16-001';
UPDATE CUSTOMER.CUSTOMER SET LAST_NAME = 'Fitzpatrick-Burke', UPDATED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = 'CUST-SIM-R16-002';
UPDATE CUSTOMER.CUSTOMER SET LAST_NAME = 'Nasser-Haddad',     UPDATED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = 'CUST-SIM-R16-003';

-- Verification
SELECT 'R17 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R17-%'
UNION ALL
SELECT 'R17 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R17-%';
