-- =============================================================================
-- Daily Load Simulation — Round 15
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Multi-account customers + phone contact additions
-- REJECTION REJ-D2: invalid email format (VR-CONT-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 14 (daily-round-14.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 15a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R15-001', 'Zara',     'Hussain',    'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R15-002', 'Eduardo',  'Castillo',   'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R15-003', 'Miriam',   'Goldstein',  'ACTIVE', 'COMMERCIAL',  'EN'),
    ('CUST-SIM-R15-004', 'Tomasz',   'Kowalski',   'ACTIVE', 'RESIDENTIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 15b. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R15-001E', 'CUST-SIM-R15-001', 'EMAIL', 'zara.hussain@demo.com'),
    ('CC-SIM-R15-002E', 'CUST-SIM-R15-002', 'EMAIL', 'eduardo.castillo@demo.com'),
    ('CC-SIM-R15-003E', 'CUST-SIM-R15-003', 'EMAIL', 'miriam.goldstein@demo.com'),
    ('CC-SIM-R15-004E', 'CUST-SIM-R15-004', 'EMAIL', 'tomasz.kowalski@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 15c. Rejection: malformed email
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CC-SIM-R15-REJE', 'CUST-SIM-R15-001', 'EMAIL', 'zarahussain-at-demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = 'CC-SIM-R15-REJE');

-- 15d. Energy accounts — including second account for multi-account customer
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R15-001', 'CUST-SIM-R15-001', 'ACCT-SIM-R15-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R15-002', 'CUST-SIM-R15-002', 'ACCT-SIM-R15-002', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R15-003', 'CUST-SIM-R15-003', 'ACCT-SIM-R15-003', 'ACTIVE', 'ELECTRIC', 'MEDIUM_COMMERCIAL'),
    ('EA-SIM-R15-004', 'CUST-SIM-R15-004', 'ACCT-SIM-R15-004', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    -- second account for R15-003 (second premises)
    ('EA-SIM-R15-B03', 'CUST-SIM-R15-003', 'ACCT-SIM-R15-B03', 'ACTIVE', 'ELECTRIC', 'SMALL_COMMERCIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 15e. Add phone contacts for Round 14 customers
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, FALSE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R14-001P', 'CUST-SIM-R14-001', 'PHONE', '555-1401'),
    ('CC-SIM-R14-002P', 'CUST-SIM-R14-002', 'PHONE', '555-1402'),
    ('CC-SIM-R14-003P', 'CUST-SIM-R14-003', 'PHONE', '555-1403')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- Verification
SELECT 'R15 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R15-%'
UNION ALL
SELECT 'R15 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R15-%';
