-- =============================================================================
-- Daily Load Simulation — Round 18
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE  |  Database: CDP_UTIL_DB  |  Warehouse: CDP_LOADER_WH
--
-- SCENARIO  Account suspensions + gas service accounts added
-- REJECTION REJ-D1: blank FIRST_NAME (VR-CUST-001)
-- TRIGGER   POST http://localhost:8080/api/jobs/daily
-- PREREQUISITE  Round 17 (daily-round-17.sql) must have been run.
-- =============================================================================

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- 18a. New customers
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CUST-SIM-R18-001', 'Aaliya',   'Kapoor',     'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R18-002', 'Fabio',    'Santini',    'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R18-003', 'Grace',    'Wanjiku',    'ACTIVE', 'RESIDENTIAL', 'EN'),
    ('CUST-SIM-R18-004', 'Hamza',    'Bouazizi',   'ACTIVE', 'COMMERCIAL',  'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = v.col1);

-- 18b. Rejection: blank FIRST_NAME
INSERT INTO CUSTOMER.CUSTOMER
    (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACCOUNT_STATUS, CUSTOMER_TYPE,
     PREFERRED_LANGUAGE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES ('CUST-SIM-R18-REJ', '', 'Void', 'ACTIVE', 'COMMERCIAL', 'EN')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID = 'CUST-SIM-R18-REJ');

-- 18c. Email contacts
INSERT INTO CUSTOMER.CUSTOMER_CONTACT
    (CONTACT_ID, CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE,
     IS_PRIMARY, IS_VERIFIED, EFFECTIVE_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, TRUE, TRUE, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('CC-SIM-R18-001E', 'CUST-SIM-R18-001', 'EMAIL', 'aaliya.kapoor@demo.com'),
    ('CC-SIM-R18-002E', 'CUST-SIM-R18-002', 'EMAIL', 'fabio.santini@demo.com'),
    ('CC-SIM-R18-003E', 'CUST-SIM-R18-003', 'EMAIL', 'grace.wanjiku@demo.com'),
    ('CC-SIM-R18-004E', 'CUST-SIM-R18-004', 'EMAIL', 'hamza.bouazizi@demo.com')
    AS v(col1,col2,col3,col4)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT WHERE CONTACT_ID = v.col1);

-- 18d. Energy accounts — includes gas service
INSERT INTO CUSTOMER.ENERGY_ACCOUNT
    (ENERGY_ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, ACCOUNT_STATUS,
     SERVICE_TYPE, RATE_CLASS, OPEN_DATE, CREATED_AT, UPDATED_AT)
SELECT col1, col2, col3, col4, col5, col6, CURRENT_DATE(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM VALUES
    ('EA-SIM-R18-001', 'CUST-SIM-R18-001', 'ACCT-SIM-R18-001', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R18-002', 'CUST-SIM-R18-002', 'ACCT-SIM-R18-002', 'ACTIVE', 'GAS',      'RESIDENTIAL'),
    ('EA-SIM-R18-003', 'CUST-SIM-R18-003', 'ACCT-SIM-R18-003', 'ACTIVE', 'ELECTRIC', 'RESIDENTIAL'),
    ('EA-SIM-R18-004', 'CUST-SIM-R18-004', 'ACCT-SIM-R18-004', 'ACTIVE', 'ELECTRIC', 'SMALL_COMMERCIAL')
    AS v(col1,col2,col3,col4,col5,col6)
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID = v.col1);

-- 18e. Suspend overdue accounts from Round 14
UPDATE CUSTOMER.ENERGY_ACCOUNT
SET ACCOUNT_STATUS = 'SUSPENDED', UPDATED_AT = CURRENT_TIMESTAMP()
WHERE ENERGY_ACCOUNT_ID IN ('EA-SIM-R14-003', 'EA-SIM-R14-004');

-- 18f. Inactivate a customer who has no balance
UPDATE CUSTOMER.CUSTOMER
SET ACCOUNT_STATUS = 'INACTIVE', STATUS_REASON = 'VOLUNTARY_CLOSURE',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CUSTOMER_ID = 'CUST-SIM-R13-004';

-- Verification
SELECT 'R18 customers' AS label, COUNT(*) AS cnt FROM CUSTOMER.CUSTOMER WHERE CUSTOMER_ID LIKE 'CUST-SIM-R18-%'
UNION ALL
SELECT 'R18 energy accounts', COUNT(*) FROM CUSTOMER.ENERGY_ACCOUNT WHERE ENERGY_ACCOUNT_ID LIKE 'EA-SIM-R18-%';
