-- =============================================================================
-- Snowflake Data Generation — Step 7: Validate Initial Dataset
-- =============================================================================
-- Run as: CDP_ADMIN_ROLE (read-only queries; CDP_LOADER_ROLE also works)
-- Database: CDP_UTIL_DB
-- Warehouse: CDP_LOADER_WH
--
-- PURPOSE
--   Run a comprehensive set of PASS/FAIL validation checks against the
--   initial dataset generated by 06-generate-initial-data.sql.
--
-- SCOPE (Issue #11 / #12)
--   This script validates the INITIAL load only.
--   Controlled invalid records (USG-INVK-% and USG-INVD-% prefixes) are introduced
--   ONLY by script 09-simulate-monthly-usage.sql and must NOT be present yet.
--   All usage quality checks (V-UQ-001 through V-UQ-007) must PASS here
--   because no invalid records have been inserted at this stage.
--   If any usage quality check FAILS here, the initial data generator has
--   a defect — this must be fixed before proceeding to script 08.
--
-- REPORT FORMAT
--   Every SELECT returns: CHECK_ID, DESCRIPTION, STATUS (PASS/FAIL/WARN),
--   OFFENDING_ROWS (0 = PASS), DETAIL
--
-- PREREQUISITE
--   06-generate-initial-data.sql must have completed successfully.
--   Script 09 (monthly simulation with invalid records) must NOT have run yet.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- PREFLIGHT — aborts immediately on wrong database or role
-- Accepts: CDP_ADMIN_ROLE or CDP_LOADER_ROLE (read-only validation script)
-- ---------------------------------------------------------------------------
EXECUTE IMMEDIATE $$
DECLARE
    wrong_database EXCEPTION (
        -20001,
        'PREFLIGHT FAILED: expected database CDP_UTIL_DB'
    );
    wrong_role EXCEPTION (
        -20002,
        'PREFLIGHT FAILED: expected role CDP_ADMIN_ROLE or CDP_LOADER_ROLE'
    );
BEGIN
    IF (CURRENT_DATABASE() <> 'CDP_UTIL_DB') THEN
        RAISE wrong_database;
    END IF;
    IF (
        CURRENT_ROLE() <> 'CDP_ADMIN_ROLE'
        AND CURRENT_ROLE() <> 'CDP_LOADER_ROLE'
    ) THEN
        RAISE wrong_role;
    END IF;
    RETURN 'PREFLIGHT PASS: CDP_UTIL_DB / ' || CURRENT_ROLE();
END;
$$;

USE ROLE CDP_ADMIN_ROLE;
USE DATABASE CDP_UTIL_DB;
USE WAREHOUSE CDP_LOADER_WH;

-- Confirm initial data exists before validating
EXECUTE IMMEDIATE $$
DECLARE
    insufficient_customers EXCEPTION (
        -20005,
        'DATA PREREQ FAILED: CUSTOMER has fewer than 10000 rows — run 06-generate-initial-data.sql first'
    );
    invalid_records_present EXCEPTION (
        -20006,
        'DATA PREREQ FAILED: USG-INVK/INVD/BZ records found — script 07 validates the INITIAL load only; script 09 must not have run yet'
    );
    cust_count INTEGER;
    inv_count  INTEGER;
BEGIN
    SELECT COUNT(*) INTO :cust_count FROM CUSTOMER.CUSTOMER;
    IF (cust_count < 10000) THEN
        RAISE insufficient_customers;
    END IF;
    SELECT COUNT(*) INTO :inv_count
    FROM BILLING.MONTHLY_USAGE
    WHERE USAGE_ID LIKE 'USG-INVK-%'
       OR USAGE_ID LIKE 'USG-INVD-%'
       OR USAGE_ID LIKE 'USG-BZ-%';
    IF (inv_count > 0) THEN
        RAISE invalid_records_present;
    END IF;
    RETURN 'Data prerequisites met — customers: ' || cust_count
        || ', invalid records absent: OK';
END;
$$;

-- Confirm no script-09 records exist yet (display check — aborting guard above already enforces this)
SELECT
    COUNT(*) AS SCENARIO_RECORD_COUNT
FROM BILLING.MONTHLY_USAGE
WHERE USAGE_ID LIKE 'USG-INVK-%'
   OR USAGE_ID LIKE 'USG-INVD-%'
   OR USAGE_ID LIKE 'USG-BZ-%';
-- Expected: 0 — script 09 must not have run yet at this point.

-- ===========================================================================
-- Section 1: Row Count Checks
-- ===========================================================================

SELECT 'V-RC-001' AS CHECK_ID,
    'CUSTOMER row count >= 10000' AS DESCRIPTION,
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
    CASE WHEN COUNT(*) >= 10000 THEN 0 ELSE 10000 - COUNT(*) END AS OFFENDING_ROWS,
    COUNT(*) || ' rows found' AS DETAIL
FROM CUSTOMER.CUSTOMER;

SELECT 'V-RC-002',
    'CUSTOMER_CONTACT row count >= 10000',
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 10000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM CUSTOMER.CUSTOMER_CONTACT;

SELECT 'V-RC-003',
    'ENERGY_ACCOUNT row count >= 10000',
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 10000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM CUSTOMER.ENERGY_ACCOUNT;

SELECT 'V-RC-004',
    'BILLING_ACCOUNT row count >= 10000',
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 10000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM CUSTOMER.BILLING_ACCOUNT;

SELECT 'V-RC-005',
    'PREMISE row count >= 10000',
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 10000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM SERVICE.PREMISE;

SELECT 'V-RC-006',
    'METER row count >= 10000',
    CASE WHEN COUNT(*) >= 10000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 10000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM SERVICE.METER;

SELECT 'V-RC-007',
    'MONTHLY_USAGE row count >= 25000 (3 months × active accounts)',
    CASE WHEN COUNT(*) >= 25000 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 25000 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM BILLING.MONTHLY_USAGE;

SELECT 'V-RC-008',
    'REF.CODE_VALUE row count >= 43 (all reference codes)',
    CASE WHEN COUNT(*) >= 43 THEN 'PASS' ELSE 'FAIL' END,
    GREATEST(0, 43 - COUNT(*)),
    COUNT(*) || ' rows found'
FROM REF.CODE_VALUE;

SELECT 'V-RC-009',
    'RATE_PLAN codes = 9',
    CASE WHEN COUNT(*) = 9 THEN 'PASS' ELSE 'FAIL' END,
    ABS(9 - COUNT(*)),
    COUNT(*) || ' rate plan rows found'
FROM REF.CODE_VALUE WHERE DOMAIN = 'RATE_PLAN';

-- ===========================================================================
-- Section 2: Orphan / Referential Integrity Checks
-- ===========================================================================

SELECT 'V-RI-001',
    'CUSTOMER_CONTACT: no orphan customer references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned contact rows'
FROM CUSTOMER.CUSTOMER_CONTACT cc
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER c WHERE c.CUSTOMER_ID = cc.CUSTOMER_ID);

SELECT 'V-RI-002',
    'ENERGY_ACCOUNT: no orphan customer references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned energy account rows'
FROM CUSTOMER.ENERGY_ACCOUNT ea
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.CUSTOMER c WHERE c.CUSTOMER_ID = ea.CUSTOMER_ID);

SELECT 'V-RI-003',
    'BILLING_ACCOUNT: no orphan energy account references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned billing account rows'
FROM CUSTOMER.BILLING_ACCOUNT ba
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT ea WHERE ea.ENERGY_ACCOUNT_ID = ba.ENERGY_ACCOUNT_ID);

SELECT 'V-RI-004',
    'PREMISE: no orphan energy account references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned premise rows'
FROM SERVICE.PREMISE p
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT ea WHERE ea.ENERGY_ACCOUNT_ID = p.ENERGY_ACCOUNT_ID);

SELECT 'V-RI-005',
    'METER: no orphan premise references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned meter rows'
FROM SERVICE.METER m
WHERE NOT EXISTS (SELECT 1 FROM SERVICE.PREMISE p WHERE p.PREMISE_ID = m.PREMISE_ID);

SELECT 'V-RI-006',
    'MONTHLY_USAGE: no orphan energy account references',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' orphaned usage rows'
FROM BILLING.MONTHLY_USAGE u
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER.ENERGY_ACCOUNT ea WHERE ea.ENERGY_ACCOUNT_ID = u.ENERGY_ACCOUNT_ID);

SELECT 'V-RI-007',
    'MONTHLY_USAGE: RATE_PLAN references valid REF.CODE_VALUE entry',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with unknown RATE_PLAN'
FROM BILLING.MONTHLY_USAGE u
WHERE NOT EXISTS (
    SELECT 1 FROM REF.CODE_VALUE rv
    WHERE rv.DOMAIN = 'RATE_PLAN' AND rv.CODE = u.RATE_PLAN AND rv.IS_ACTIVE = TRUE
);

-- ===========================================================================
-- Section 3: Duplicate Business Key Checks
-- ===========================================================================

SELECT 'V-DK-001',
    'CUSTOMER: no duplicate CUSTOMER_ID',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' duplicate CUSTOMER_ID groups'
FROM (SELECT CUSTOMER_ID FROM CUSTOMER.CUSTOMER GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1);

SELECT 'V-DK-002',
    'ENERGY_ACCOUNT: no duplicate ACCOUNT_NUMBER',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' duplicate ACCOUNT_NUMBER groups'
FROM (SELECT ACCOUNT_NUMBER FROM CUSTOMER.ENERGY_ACCOUNT GROUP BY ACCOUNT_NUMBER HAVING COUNT(*) > 1);

SELECT 'V-DK-003',
    'METER: no duplicate METER_NUMBER',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' duplicate METER_NUMBER groups'
FROM (SELECT METER_NUMBER FROM SERVICE.METER GROUP BY METER_NUMBER HAVING COUNT(*) > 1);

SELECT 'V-DK-004',
    'MONTHLY_USAGE: no duplicate (ENERGY_ACCOUNT_ID, BILLING_MONTH)',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' duplicate billing month groups'
FROM (
    SELECT ENERGY_ACCOUNT_ID, BILLING_MONTH
    FROM BILLING.MONTHLY_USAGE
    GROUP BY ENERGY_ACCOUNT_ID, BILLING_MONTH
    HAVING COUNT(*) > 1
);

SELECT 'V-DK-005',
    'REF.CODE_VALUE: no duplicate (DOMAIN, CODE)',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' duplicate domain/code groups'
FROM (SELECT DOMAIN, CODE FROM REF.CODE_VALUE GROUP BY DOMAIN, CODE HAVING COUNT(*) > 1);

-- ===========================================================================
-- Section 4: Mandatory Field Checks
-- ===========================================================================

SELECT 'V-MF-001',
    'CUSTOMER: FIRST_NAME / LAST_NAME / ACCOUNT_STATUS not null',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with missing mandatory fields'
FROM CUSTOMER.CUSTOMER
WHERE FIRST_NAME IS NULL OR LAST_NAME IS NULL OR ACCOUNT_STATUS IS NULL;

SELECT 'V-MF-002',
    'ENERGY_ACCOUNT: RATE_CLASS / ACCOUNT_NUMBER not null',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with missing mandatory fields'
FROM CUSTOMER.ENERGY_ACCOUNT
WHERE RATE_CLASS IS NULL OR ACCOUNT_NUMBER IS NULL;

SELECT 'V-MF-003',
    'MONTHLY_USAGE: KWH_USAGE / RATE_PLAN / BILLING_MONTH not null',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with missing mandatory fields'
FROM BILLING.MONTHLY_USAGE
WHERE KWH_USAGE IS NULL OR RATE_PLAN IS NULL OR BILLING_MONTH IS NULL;

SELECT 'V-MF-004',
    'BILLING_ACCOUNT: BILLING_ACCOUNT_NBR / BILLING_CYCLE not null',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with null billing account fields'
FROM CUSTOMER.BILLING_ACCOUNT
WHERE BILLING_ACCOUNT_NBR IS NULL OR BILLING_CYCLE IS NULL;

-- ===========================================================================
-- Section 5: Invalid Status / Reference Code Checks
-- ===========================================================================

SELECT 'V-CV-001',
    'CUSTOMER: ACCOUNT_STATUS is a valid code',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with invalid ACCOUNT_STATUS'
FROM CUSTOMER.CUSTOMER
WHERE ACCOUNT_STATUS NOT IN ('ACTIVE','INACTIVE','PENDING','CLOSED','SUSPENDED');

SELECT 'V-CV-002',
    'CUSTOMER: CUSTOMER_TYPE is a valid code',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with invalid CUSTOMER_TYPE'
FROM CUSTOMER.CUSTOMER
WHERE CUSTOMER_TYPE NOT IN ('RESIDENTIAL','COMMERCIAL','INDUSTRIAL');

SELECT 'V-CV-003',
    'MONTHLY_USAGE: READ_TYPE is ACTUAL or ESTIMATED',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with invalid READ_TYPE'
FROM BILLING.MONTHLY_USAGE
WHERE READ_TYPE NOT IN ('ACTUAL','ESTIMATED');

SELECT 'V-CV-004',
    'METER: METER_TYPE is a valid code',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with invalid METER_TYPE'
FROM SERVICE.METER
WHERE METER_TYPE NOT IN ('ANALOG','DIGITAL','AMI');

SELECT 'V-CV-005',
    'PREMISE: STATE_CODE is 2 characters',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with invalid STATE_CODE length'
FROM SERVICE.PREMISE
WHERE LENGTH(STATE_CODE) != 2 OR STATE_CODE IS NULL;

-- ===========================================================================
-- Section 6: Usage Data Quality Checks
-- ===========================================================================

SELECT 'V-UQ-001',
    'MONTHLY_USAGE: no negative KWH_USAGE',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with negative KWH'
FROM BILLING.MONTHLY_USAGE WHERE KWH_USAGE < 0;

SELECT 'V-UQ-002',
    'MONTHLY_USAGE: no negative PEAK_DEMAND_KW',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with negative peak demand'
FROM BILLING.MONTHLY_USAGE WHERE PEAK_DEMAND_KW IS NOT NULL AND PEAK_DEMAND_KW < 0;

SELECT 'V-UQ-003',
    'MONTHLY_USAGE: CURR_METER_READING >= PREV_METER_READING',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows where current reading < previous reading'
FROM BILLING.MONTHLY_USAGE
WHERE CURR_METER_READING IS NOT NULL
  AND PREV_METER_READING IS NOT NULL
  AND CURR_METER_READING < PREV_METER_READING;

SELECT 'V-UQ-004',
    'MONTHLY_USAGE: BILL_END_DATE >= BILL_START_DATE',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with inverted billing period'
FROM BILLING.MONTHLY_USAGE WHERE BILL_END_DATE < BILL_START_DATE;

SELECT 'V-UQ-005',
    'MONTHLY_USAGE: BILLING_DAYS between 1 and 45',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with unreasonable BILLING_DAYS'
FROM BILLING.MONTHLY_USAGE WHERE BILLING_DAYS < 1 OR BILLING_DAYS > 45;

SELECT 'V-UQ-006',
    'MONTHLY_USAGE: no negative TOTAL_BILLED',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with negative TOTAL_BILLED'
FROM BILLING.MONTHLY_USAGE WHERE TOTAL_BILLED IS NOT NULL AND TOTAL_BILLED < 0;

SELECT 'V-UQ-007',
    'MONTHLY_USAGE: no negative charges (FIXED, ENERGY, DEMAND, TAX)',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with a negative charge component'
FROM BILLING.MONTHLY_USAGE
WHERE (FIXED_CHARGE IS NOT NULL AND FIXED_CHARGE < 0)
   OR (ENERGY_CHARGE IS NOT NULL AND ENERGY_CHARGE < 0)
   OR (DEMAND_CHARGE IS NOT NULL AND DEMAND_CHARGE < 0)
   OR (TAX_AMOUNT    IS NOT NULL AND TAX_AMOUNT    < 0);

-- ===========================================================================
-- Section 7: Contact Constraint Checks
-- ===========================================================================

SELECT 'V-CC-001',
    'CUSTOMER_CONTACT: each customer has exactly 1 primary email',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' customers with != 1 primary email'
FROM (
    SELECT CUSTOMER_ID, COUNT(*) AS CNT
    FROM CUSTOMER.CUSTOMER_CONTACT
    WHERE CONTACT_TYPE = 'EMAIL' AND IS_PRIMARY = TRUE
      AND (END_DATE IS NULL OR END_DATE >= CURRENT_DATE())
    GROUP BY CUSTOMER_ID
    HAVING CNT != 1
);

SELECT 'V-CC-002',
    'CUSTOMER: every customer has at least one contact record',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' customers with no contact records'
FROM CUSTOMER.CUSTOMER c
WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOMER.CUSTOMER_CONTACT cc WHERE cc.CUSTOMER_ID = c.CUSTOMER_ID
);

-- ===========================================================================
-- Section 8: Meter Constraint Checks
-- ===========================================================================

SELECT 'V-MC-001',
    'SERVICE.METER: each active premise has at most 1 active meter',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' premises with > 1 active meter'
FROM (
    SELECT PREMISE_ID, COUNT(*) AS CNT
    FROM SERVICE.METER
    WHERE IS_ACTIVE = TRUE
      AND (REMOVAL_DATE IS NULL OR REMOVAL_DATE >= CURRENT_DATE())
    GROUP BY PREMISE_ID
    HAVING CNT > 1
);

SELECT 'V-MC-002',
    'Every active PREMISE has at least one meter',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' active premises with no meter'
FROM SERVICE.PREMISE p
WHERE p.END_DATE IS NULL
  AND NOT EXISTS (SELECT 1 FROM SERVICE.METER m WHERE m.PREMISE_ID = p.PREMISE_ID);

-- ===========================================================================
-- Section 9: UPDATED_AT Coverage Check
-- ===========================================================================

SELECT 'V-TS-001',
    'CUSTOMER: UPDATED_AT >= CREATED_AT',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows where UPDATED_AT < CREATED_AT'
FROM CUSTOMER.CUSTOMER WHERE UPDATED_AT < CREATED_AT;

SELECT 'V-TS-002',
    'MONTHLY_USAGE: UPDATED_AT >= CREATED_AT',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows where UPDATED_AT < CREATED_AT'
FROM BILLING.MONTHLY_USAGE WHERE UPDATED_AT < CREATED_AT;

SELECT 'V-TS-003',
    'CUSTOMER: all UPDATED_AT values are non-null',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*),
    COUNT(*) || ' rows with NULL UPDATED_AT'
FROM CUSTOMER.CUSTOMER WHERE UPDATED_AT IS NULL;

-- ===========================================================================
-- Section 10: Summary report
-- ===========================================================================
SELECT
    'SUMMARY' AS CHECK_ID,
    'Initial data validation complete — check individual results above' AS DESCRIPTION,
    'INFO' AS STATUS,
    0 AS OFFENDING_ROWS,
    'Run each check above individually; FAIL indicates data quality issue' AS DETAIL;
